// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI only (migrate, studio) — the app's runtime pool reads DATABASE_URL
    // separately. `migrate deploy` takes a session-level advisory lock, which
    // times out (P1002) through Neon's PgBouncer `-pooler` host, so prefer a
    // direct connection when one is configured.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
